#!/usr/bin/env python3

# Copyright (C) Arthur Reutenauer 3 April 2020
# MIT licence (https://opensource.org/licenses/MIT)

from hyphenator import Hyphenator
from nltk.grammar import CFG
from nltk.parse.generate import generate
from os.path import join as joinpath
from pathlib import Path
from requests import get as httpget
import tarfile
from tempfile import TemporaryDirectory
from time import sleep
from xml.etree import ElementTree as ET

# Downloading the dictionary from Kotus if it’ not in the working directory.
dictfname = 'kotus-sanalista_v1/kotus-sanalista_v1.xml'
hyphfname = 'src/hyph-fi-x-basic.pat.txt'
if not Path(dictfname).exists():
  print('Fetching Kotus’ word list ...')
  response = httpget('http://kaino.kotus.fi/sanat/nykysuomi/kotus-sanalista-v1.tar.gz')

  with TemporaryDirectory() as tempdir:
    tarfname = joinpath(tempdir, 'dict.tar.gz')
    with open(tarfname, 'wb') as tarf:
      tarf.write(response.content)
    tar = tarfile.open(tarfname, 'r:gz')
    print('  Extracting ...')
    dictfcontents = tar.extractfile(dictfname)
    with open(dictfname, 'wb') as dictf:
      dictf.write(dictfcontents.read())
      print('  Done.')

# TODO: ‘c’
# Generate the patterns from a context-free grammar.
pattern_grammar = CFG.fromstring("""
  S -> '1' K V | V '1' V | D | VV | DOTKK | REST
  V -> BACK | FRONT | NEUTRAL
  K -> OBSTRUENT | LIQUID | SIBILANTS | NASALS | GLIDES
  BACK -> 'a' | 'o' | 'u'
  NEUTRAL -> 'e' | 'i'
  FRONT -> 'ä' | 'ö' | 'y'
  OBSTRUENT -> 'b' | 'd' | 'f' | 'g' | 'k' | 'p' | 's' | 't' | 'v'
  LIQUID -> 'l' | 'r'
  NASALS -> 'm' | 'n'
  GLIDES -> 'h' | 'j'
  SIBILANTS -> 's' | 'š' | 'z' | 'ž'
  D -> 'a2i' | 'e2i' | 'o2i' | 'ä2i' | 'ö2i' | 'e2y' | 'ä2y' | 'ö2y' | 'a2u' | 'e2u' | 'o2u' | 'u2i' | 'y2i' | 'i2u' | 'i2y' | 'i2e' | 'u2o' | 'y2ö'
  VV -> 'a2a' | 'e2e' | 'i2i' | 'o2o' | 'u2u' | 'y2y' | 'ä2ä' | 'ö2ö'
  DOTKK -> '.' OBSTRUENT '2' LIQUID '2' | '.g2n2' | '.k2h2' | '.k2n2' | '.k2s2' | '.k2v2' | '.p2n2' | '.p2s2' | '.s2h2' | '.s2k2' | '.s2m2' | '.s2n2' | '.s2p2' | '.s2t2' | '.s2v2' | '.t2h2' | '.t2s2' | '.t2š2' | '.t2v2' | '.d2ž2' | '.g2h2' | '.p2h2' | '.p2t2' | '.r2h2' | '.s2f2' | '.z2l2'
  REST -> '.d2n2a' | '.l2v2i'
""")

# sr and zr don’t appear at the beginning of words, OBSTRUENT LIQUID is still a good approximation.
# vr and vl don’t appear either

# Generating the patterns
print('Generating patterns ...')
with open(hyphfname, 'w') as pattfile:
  pattfile.write("UTF-8\n")
  for patt in generate(pattern_grammar):
    pattfile.write(''.join(patt))
    pattfile.write("\n")

# Hyphenate the word list
hyphenator = Hyphenator(hyphfname, 1)
lexicon = ET.parse(dictfname)
with open('list/hyphenated.txt', 'w') as listfile:
  for node in lexicon.getroot():
    sana = node[0].text
    pos = hyphenator.positions(sana)
    letters = [('-' if i in pos and sana[i-1] != '-' and sana[i-1] != ' ' else '') + sana[i] for i in range(len(sana))]
    hyphenated = ''.join(letters)
    print(hyphenated)
    listfile.write(''.join(hyphenated))
    listfile.write("\n")
